from gitscribe.git import filters, reader


def _make_history(repo):
    """main: c1 (root) -> c2 -> merge(feature: f1, f2) -> c3 [tag v0.1 on c2]"""
    repo.write("app/main.py", "def main():\n    return 1\n")
    repo.write("package-lock.json", '{"lockfileVersion": 3}\n')
    repo.write(".DS_Store", b"\x00\x01\x02binary")
    repo.write("logo.png", b"\x89PNG\x00\x00")
    c1 = repo.commit("Initial commit", "2026-01-05T10:00:00+00:00")

    repo.write("app/main.py", "def main():\n        return 1\n")  # whitespace-only
    repo.write("package-lock.json", '{"lockfileVersion": 4}\n')
    c2 = repo.commit("Reindent", "2026-01-06T10:00:00+00:00")
    repo.git("tag", "v0.1")

    repo.git("checkout", "-q", "-b", "feature")
    repo.write("app/util.py", "def helper(x):\n    return x * 2\n")
    f1 = repo.commit("Add helper", "2026-01-13T10:00:00+00:00")
    repo.write("app/main.py", "from app.util import helper\n\ndef main():\n    return helper(1)\n")
    f2 = repo.commit("Use helper", "2026-01-13T11:00:00+00:00")
    repo.git("checkout", "-q", "main")
    repo.write("README.md", "# demo\n")
    c3 = repo.commit("Add readme", "2026-01-14T09:00:00+00:00")
    repo.git("merge", "-q", "--no-ff", "feature", "-m", "Merge pull request #1 from feature", date="2026-01-14T10:00:00+00:00")
    m = repo.head()
    return dict(c1=c1, c2=c2, f1=f1, f2=f2, c3=c3, m=m)


def test_read_commits_oldest_first_and_since(repo):
    shas = _make_history(repo)
    r = reader.open_repo(str(repo.path))
    commits = reader.read_commits(r)
    assert commits[0].sha == shas["c1"]
    assert commits[-1].sha == shas["m"]
    assert commits[-1].is_merge
    assert len(commits) == 6

    newer = reader.read_commits(r, since_sha=shas["c2"])
    assert {c.sha for c in newer} == {shas["f1"], shas["f2"], shas["c3"], shas["m"]}


def test_file_diffs_root_merge_and_binary(repo):
    shas = _make_history(repo)
    r = reader.open_repo(str(repo.path))

    root = {d.path: d for d in reader.file_diffs(r, shas["c1"])}
    assert root["app/main.py"].change_type == "A"
    assert root["app/main.py"].additions == 2
    assert "+def main():" in root["app/main.py"].diff
    assert root[".DS_Store"].is_binary

    assert reader.file_diffs(r, shas["m"]) == []

    f2 = reader.file_diffs(r, shas["f2"])
    assert [d.change_type for d in f2] == ["M"]


def test_rename_detected(repo):
    repo.write("a.py", "x = 1\ny = 2\nz = 3\n")
    repo.commit("add")
    repo.git("mv", "a.py", "b.py")
    sha = repo.commit("rename")
    r = reader.open_repo(str(repo.path))
    (d,) = reader.file_diffs(r, sha)
    assert (d.change_type, d.old_path, d.path) == ("R", "a.py", "b.py")
    assert filters.skip_reason(d) is None


def test_filters_drop_noise_keep_real_changes(repo):
    shas = _make_history(repo)
    r = reader.open_repo(str(repo.path))
    diffs = [d for c in reader.read_commits(r) for d in reader.file_diffs(r, c.sha)]
    result = filters.filter_diffs(diffs, max_diff_chars=10_000)

    reasons = {(s.commit_sha, s.path): s.reason for s in result.skipped}
    assert reasons[(shas["c1"], "package-lock.json")] == "lockfile"
    assert reasons[(shas["c1"], ".DS_Store")] == "os-junk"
    assert reasons[(shas["c1"], "logo.png")] == "binary"
    assert reasons[(shas["c2"], "app/main.py")] == "whitespace-only"

    kept = {(d.commit_sha, d.path) for d in result.kept}
    assert kept == {
        (shas["c1"], "app/main.py"),
        (shas["f1"], "app/util.py"),
        (shas["f2"], "app/main.py"),
        (shas["c3"], "README.md"),
    }


def test_path_rules():
    assert filters.path_skip_reason("web/node_modules/x/index.js") == "vendored/build output"
    assert filters.path_skip_reason("api/v1/service.pb.go") == "generated"
    assert filters.path_skip_reason("static/app.min.js") == "generated"
    assert filters.path_skip_reason("src/app.py") is None


def test_whitespace_detection_handles_rewrap():
    patch = "@@ -1,2 +1,1 @@\n-foo(a,\n-    b)\n+foo(a, b)\n"
    assert filters.is_whitespace_only(patch)
    assert not filters.is_whitespace_only("@@ -1 +1 @@\n-foo(a)\n+foo(b)\n")


def test_timestamp_only_migration_skipped():
    fd = reader.FileDiff(
        commit_sha="x",
        path="db/migrations/0001_init.py",
        old_path=None,
        change_type="M",
        diff="@@ -1 +1 @@\n-# Generated by Django 4.2 on 2024-01-01 10:00\n+# Generated by Django 4.2 on 2024-02-01 11:00\n",
        is_binary=False,
        additions=1,
        deletions=1,
    )
    assert filters.skip_reason(fd) == "timestamp-only"


def test_truncate_keeps_whole_hunks():
    hunk = "@@ -1,3 +1,3 @@\n" + "".join(f"+line {i}\n" for i in range(50))
    patch = hunk * 4
    out = filters.truncate_diff(patch, max_chars=len(hunk) * 2 + 10)
    assert out.count("@@ -1,3 +1,3 @@") == 2
    assert "diff truncated" in out
    assert filters.truncate_diff("short", 100) == "short"
    assert "diff truncated" in filters.truncate_diff("@@ x\n" + "y\n" * 500, 50)


def test_batches_by_pr_week_tag(repo):
    shas = _make_history(repo)
    r = reader.open_repo(str(repo.path))
    commits = reader.read_commits(r)

    batches, sections = reader.make_batches(r, commits, "pr")
    assert [s.label for s in sections] == ["v0.1", reader.UNRELEASED]
    # main line: direct commits c1, c2 (v0.1) and c3 (unreleased) are grouped per release,
    # then the merge brings in f1, f2
    assert [b.commit_shas for b in batches] == [
        [shas["c1"], shas["c2"]],
        [shas["c3"]],
        [shas["f1"], shas["f2"], shas["m"]],
    ]
    assert batches[2].label == "Merge pull request #1 from feature"
    assert [b.section for b in batches] == ["v0.1", reader.UNRELEASED, reader.UNRELEASED]

    weekly, _ = reader.make_batches(r, commits, "week")
    assert [b.label for b in weekly] == ["Week 2026-W02", "Week 2026-W03"]

    tagged, _ = reader.make_batches(r, commits, "tag")
    assert [(b.label, set(b.commit_shas)) for b in tagged] == [
        ("v0.1", {shas["c1"], shas["c2"]}),
        (reader.UNRELEASED, {shas["f1"], shas["f2"], shas["c3"], shas["m"]}),
    ]
    assert tagged[0].section == "v0.1"
